### PR TITLE
Generators of config files

### PR DESCRIPTION
**Pull request by the-homeless-god**
- Added entry point
- Added font installation
- Updated README
- Added a generator for Mac OS for .zshrc
- Added a generator for Tmux configuration file
- Added a generator for Alacritty configuration
- Removed .zshrc because it provides user data
- Removed .tmux.conf because it can be autogenerated
- Removed alacritty.yml because it can be autogenerated
- Removed wallpapers directory
- Removed bin directory, because it should not provide ref to bin

### CODE REVIEW

**Comment by the-homeless-god** [comment]
@solidiquis PTAL

**Comment by solidiquis** [comment]
Thanks @Zimtir ! Not sure why you did this.. but it's very informative! Much appreciated! I'll be taking a look over the next few days.

**Comment by the-homeless-god** [comment]
@solidiquis I think that anyone should have ability to use your dotfiles by simple clonning and execution on installation :)

I think we should make a great experience with this one and make trends 🥇

**Comment by the-homeless-god** [comment]
@solidiquis did you have a time to take a look?

**Pull request closed without merging**
